{
  "openapi": "3.0.1",
  "info": {
    "version": "1",
    "title": "Your pet API",
    "description": "This is API for selling pets, adding them to favorites, describing your pet, etc.",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [{ "url": "https://your-pet-shw3.onrender.com" }],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Notice",
      "description": "Notice's endpoints"
    },
    {
      "name": "Pets",
      "description": "Pet endpoints"
    }
  ],
  "paths": {
    "/users/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorBadRequestResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "409": {
            "description": "Provided email already exists",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorConflictEmailResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/users/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorBadRequestResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/users/update": {
      "patch": {
        "tags": ["Auth"],
        "summary": "Update user information",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Update user's object (multipart/form-data)",
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UserUpdateRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation, user update",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserUpdateResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorBadRequestResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": ["Auth"],
        "summary": "Get current user",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetCurrentUserResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/users/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "Successful operation, No content"
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },

    "/notices": {
      "get": {
        "tags": ["Notice"],
        "summary": "Get notices by category and/or search parameters",
        "parameters": [
          {
            "in": "query",
            "name": "NoticesCategoriesNav",
            "description": "Notices category",
            "explode": true,
            "schema": {
              "type": "string",
              "default": "sell",
              "enum": ["sell", "lost-found", "in-good-hands"]
            }
          },
          {
            "in": "query",
            "name": "NoticesSearch",
            "description": "Notices search parameter (search by title)",
            "schema": {
              "type": "string",
              "default": "empty string",
              "example": "cat"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetNoticesResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Notice"],
        "summary": "Add notices by chose category",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Notice's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddNoticeRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddNoticeResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/notices/favorite": {
      "get": {
        "tags": ["Notice"],
        "summary": "Get favorite notices autorizated user",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetFavoriteNoticesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/notices/{noticeId}": {
      "get": {
        "tags": ["Notice"],
        "summary": "Get notice by id",
        "parameters": [
          {
            "in": "path",
            "name": "noticeId",
            "required": true,
            "description": "Notice's id",
            "schema": {
              "type": "string",
              "example": "64e251e974992f975f71c4ee"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetNoticeByIdResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Notice"],
        "summary": "Delete owner notice by id",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "noticeId",
            "required": true,
            "description": "Notice's id",
            "schema": {
              "type": "string",
              "example": "64e251e974992f975f71c4ee"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RemoveOwnerNoticeResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/notices/{noticeId}/addFavorite": {
      "patch": {
        "tags": ["Notice"],
        "summary": "Add notice to favorite by id",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "noticeId",
            "required": true,
            "description": "Notice's id",
            "schema": {
              "type": "string",
              "example": "64e251e974992f975f71c4ee"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddNoticeToFavoriteResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/notices/{noticeId}/removeFavorite": {
      "patch": {
        "tags": ["Notice"],
        "summary": "Remove notice from favorite by id",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "noticeId",
            "required": true,
            "description": "Notice's id",
            "schema": {
              "type": "string",
              "example": "64e251e974992f975f71c4ee"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RemoveNoticeFromFavoriteResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/notices/userNotices": {
      "get": {
        "tags": ["Notice"],
        "summary": "Get owner user's notices",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUserNoticesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorUnauthorizedResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorNotFoundResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorServerResponse"
                }
              }
            }
          }
        }
      }
    },
    "/pet": {
      "post": {
        "tags": ["Pets"],
        "summary": "Add animal card",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/pet/{petId}": {
      "delete": {
        "tags": ["Pets"],
        "summary": "Removing the animal card",
        "responses": {
          "200": {
            "description": "Successful operation"
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "Pet with id not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Name"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "Qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string",
                "describing": "User's id",
                "example": "534d677fcc8ea7aedaabc1"
              },
              "name": {
                "type": "string",
                "description": "User's name",
                "example": "Taras"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email",
                "example": "Taras@gmail.com"
              },
              "avatarURL": {
                "type": "string",
                "description": "User's avatar link",
                "example": "//www.gravatar.com/avatar/1aedb8d9dc4751e229a335e371db8058"
              }
            }
          },
          "token": {
            "type": "string",
            "description": "User's token",
            "example": "32143232436545474"
          }
        },
        "example": {
          "user": {
            "_id": "3444542njnj54khbhb45bhk",
            "name": "Taras",
            "email": "Taras@gmail.com",
            "avatarURL": "//www.gravatar.com/avatar/1aedb8ddc4751e229a335e371db805"
          },
          "token": "32143232436545474"
        }
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "Qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string",
                "describing": "User's id",
                "example": "534d677fcc8ea7aedaabc1"
              },
              "name": {
                "type": "string",
                "description": "User's name",
                "example": "Taras"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email",
                "example": "Taras@gmail.com"
              },
              "avatarURL": {
                "type": "string",
                "description": "User's avatar link",
                "example": "//www.gravatar.com/avatar/1aedb8d9dc4751e229a335e371db8058"
              }
            }
          },
          "token": {
            "type": "string",
            "description": "User's token",
            "example": "32143232436545474"
          }
        },
        "example": {
          "user": {
            "_id": "3444542njnj54khbhb45bhk",
            "name": "Taras",
            "email": "Taras@gmail.com",
            "avatarURL": "//www.gravatar.com/avatar/1aedb8ddc4751e229a335e371db805"
          },
          "token": "32143232436545474"
        }
      },
      "GetCurrentUserResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "describing": "User's id",
            "example": "534d677fcc8ea7aedaabc1"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Taras"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "Taras@gmail.com"
          },
          "avatarURL": {
            "type": "string",
            "description": "User's avatar link",
            "example": "//www.gravatar.com/avatar/1aedb8d9dc4751e229a335e371db8058"
          },
          "birthday": {
            "type": "string",
            "description": "User's birthday",
            "example": "23-11-2023"
          },
          "phone": {
            "type": "string",
            "description": "User's phone",
            "example": "+38099943"
          },
          "location": {
            "type": "string",
            "description": "User's location",
            "example": "Lviv"
          }
        },
        "example": {
          "_id": "3444542njnj54khbhb45bhk",
          "name": "Taras",
          "email": "Taras@gmail.com",
          "avatarURL": "//www.gravatar.com/avatar/1aeb8d9dc4751e229a335e371db8058",
          "birthday": "23-11-2023",
          "phone": "+38099943",
          "location": "Lviv"
        }
      },
      "UserUpdateRequest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Taras"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "avatar": {
            "type": "file",
            "format": "binary",
            "description": "User's avatar file",
            "example": "avatar.jpg"
          },
          "birthday": {
            "type": "string",
            "description": "User's birthday",
            "example": "23-12-2023"
          },
          "phone": {
            "type": "string",
            "description": "User's phone number",
            "example": "+38097485495"
          },
          "city": {
            "type": "string",
            "description": "User's city",
            "example": "Lviv"
          }
        }
      },
      "UserUpdateResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "describing": "User's id",
            "example": "534d677fcc8ea7aedaabc1"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Taras"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "avatarURL": {
            "type": "string",
            "description": "User's avatar link",
            "example": "//www.gravatar.com/avatar/1aedb8ddc4751e229a335e371db805"
          },
          "birthday": {
            "type": "string",
            "description": "User's birthday",
            "example": "23-12-2023"
          },
          "phone": {
            "type": "string",
            "description": "User's phone number",
            "example": "+38097485495"
          },
          "city": {
            "type": "string",
            "description": "User's city",
            "example": "Lviv"
          }
        },
        "example": {
          "_id": "3444542njnj54khbhb45bhk",
          "name": "Taras",
          "email": "user@example.com",
          "avatarURL": "//www.gravatar.com/avatar/1aedb8d9dc4751e229a335e371db8058",
          "birthday": "23-12-2023",
          "phone": "+38097485495",
          "city": "Lviv"
        }
      },

      "GetNoticesResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "description": "Notice's title",
              "example": "Cute cat looking for a home"
            },
            "petAvatarURL": {
              "type": "string",
              "description": "Pet's foto link",
              "example": "https://loremflickr.com/640/480/animals"
            },
            "name": {
              "type": "string",
              "description": "Pet's name",
              "example": "Melany"
            },
            "birthday": {
              "type": "string",
              "description": "Pet's birthday",
              "example": "21-09-2023"
            },
            "type": {
              "type": "string",
              "description": "Pet's type",
              "example": "Promeranian"
            },
            "sex": {
              "type": "string",
              "description": "Pet's sex",
              "enum": ["male", "female"],
              "example": "male"
            },
            "comments": {
              "type": "string",
              "description": "Notice's comments",
              "example": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!"
            },
            "location": {
              "type": "string",
              "description": "Pet's city",
              "example": "Barnstable Town"
            },
            "category": {
              "type": "string",
              "description": "Notice's category",
              "enum": ["sell", "lost/found", "in good hands"],
              "example": "lost/found"
            },
            "price": {
              "type": "number",
              "description": "Pet's price",
              "example": "23"
            },
            "owner": {
              "type": "string",
              "description": "Owner's id",
              "example": "534d677fcc8ea74aedaabdc1"
            },
            "idUsersAddedFavorite": {
              "type": "array",
              "description": "User's id who added notice favorite",
              "item": {
                "type": "string",
                "describe": "User's id",
                "example": "64df88ca1f2426eddf5014d7"
              }
            }
          }
        },
        "example": [
          {
            "title": "Cute pet looking for a home",
            "petAvatarURL": "https://loremflickr.com/640/480/animals",
            "name": "Charlie",
            "birthday": "21-09-2023",
            "type": "Promeranian",
            "sex": "male",
            "place": "Little Rock",
            "comments": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!",
            "category": "sell",
            "price": "40",
            "owner": "f24cf26ff2b7a80e999b8abb",
            "idUsersAddedFavorite": [
              "64df88ca1f2426eddf5014d7",
              "75df88ca1f6346eddf5014g6"
            ]
          },
          {
            "title": "Cute pet looking for a home",
            "petAvatarURL": "https://loremflickr.com/640/480/animals",
            "name": "Charlie",
            "birthday": "21-09-2023",
            "type": "Promeranian",
            "sex": "male",
            "place": "Little Rock",
            "comments": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!",
            "category": "sell",
            "price": "40",
            "owner": "f24cf26ff2b7a80e999b8abb",
            "idUsersAddedFavorite": [
              "64df88ca1f2426eddf5014d7",
              "75df88ca1f6346eddf5014g6"
            ]
          }
        ]
      },
      "GetFavoriteNoticesResponse": {
        "type": "array",
        "properties": {
          "title": {
            "type": "string",
            "description": "Notice's title",
            "example": "Cute cat looking for a home"
          },
          "petAvatarURL": {
            "type": "string",
            "description": "Pet's foto link",
            "example": "https://loremflickr.com/640/480/animals"
          },
          "name": {
            "type": "string",
            "description": "Pet's name",
            "example": "Melany"
          },
          "birthday": {
            "type": "string",
            "description": "Pet's birthday",
            "example": "21-09-2023"
          },
          "type": {
            "type": "string",
            "description": "Pet's type",
            "example": "Promeranian"
          },
          "sex": {
            "type": "string",
            "description": "Pet's sex",
            "enum": ["male", "female"],
            "example": "male"
          },
          "comments": {
            "type": "string",
            "description": "Notice's comments",
            "example": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!"
          },
          "location": {
            "type": "string",
            "description": "Pet's city",
            "example": "Barnstable Town"
          },
          "category": {
            "type": "string",
            "description": "Notice's category",
            "enum": ["sell", "lost/found", "in good hands"],
            "example": "lost/found"
          },
          "price": {
            "type": "number",
            "description": "Pet's price",
            "example": "23"
          },
          "owner": {
            "type": "string",
            "description": "Owner's id",
            "example": "534d677fcc8ea74aedaabdc1"
          },
          "idUsersAddedFavorite": {
            "type": "array",
            "description": "User's id who added notice favorite",
            "item": {
              "type": "string",
              "describe": "User's id",
              "example": "64df88ca1f2426eddf5014d7"
            }
          }
        },
        "example": [
          {
            "title": "Cute pet looking for a home",
            "petAvatarURL": "https://loremflickr.com/640/480/animals",
            "name": "Charlie",
            "birthday": "21-09-2023",
            "type": "Promeranian",
            "sex": "male",
            "place": "Little Rock",
            "comments": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!",
            "category": "sell",
            "price": "40",
            "owner": "f24cf26ff2b7a80e999b8abb",
            "idUsersAddedFavorite": [
              "64df88ca1f2426eddf5014d7",
              "75df88ca1f6346eddf5014g6"
            ]
          },
          {
            "title": "Cute pet looking for a home",
            "petAvatarURL": "https://loremflickr.com/640/480/animals",
            "name": "Charlie",
            "birthday": "21-09-2023",
            "type": "Promeranian",
            "sex": "male",
            "place": "Little Rock",
            "comments": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!",
            "category": "sell",
            "price": "40",
            "owner": "f24cf26ff2b7a80e999b8abb",
            "idUsersAddedFavorite": [
              "64df88ca1f2426eddf5014d7",
              "75df88ca1f6346eddf5014g6"
            ]
          }
        ]
      },
      "GetNoticeByIdResponse": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Notice's title",
            "example": "Cute cat looking for a home"
          },
          "petAvatarURL": {
            "type": "string",
            "description": "Pet's foto link",
            "example": "https://loremflickr.com/640/480/animals"
          },
          "name": {
            "type": "string",
            "description": "Pet's name",
            "example": "Melany"
          },
          "birthday": {
            "type": "string",
            "description": "Pet's birthday",
            "example": "21-09-2023"
          },
          "type": {
            "type": "string",
            "description": "Pet's type",
            "example": "Promeranian"
          },
          "sex": {
            "type": "string",
            "description": "Pet's sex",
            "enum": ["male", "female"],
            "example": "male"
          },
          "comments": {
            "type": "string",
            "description": "Notice's comments",
            "example": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!"
          },
          "location": {
            "type": "string",
            "description": "Pet's city",
            "example": "Barnstable Town"
          },
          "category": {
            "type": "string",
            "description": "Notice's category",
            "enum": ["sell", "lost/found", "in good hands"],
            "example": "lost/found"
          },
          "price": {
            "type": "number",
            "description": "Pet's price",
            "example": "23"
          },
          "owner": {
            "type": "string",
            "description": "Owner's id",
            "example": "534d677fcc8ea74aedaabdc1"
          },
          "idUsersAddedFavorite": {
            "type": "array",
            "description": "User's id who added notice favorite",
            "item": {
              "type": "string",
              "describe": "User's id",
              "example": "64df88ca1f2426eddf5014d7"
            }
          }
        },
        "example": {
          "title": "Cute pet looking for a home",
          "petAvatarURL": "https://loremflickr.com/640/480/animals",
          "name": "Charlie",
          "birthday": "21-09-2023",
          "type": "Promeranian",
          "sex": "male",
          "place": "Little Rock",
          "comments": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!",
          "category": "sell",
          "price": "40",
          "owner": "f24cf26ff2b7a80e999b8abb",
          "idUsersAddedFavorite": [
            "64df88ca1f2426eddf5014d7",
            "75df88ca1f6346eddf5014g6"
          ]
        }
      },
      "AddNoticeToFavoriteResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Successful operation",
            "example": "Notice successfully add to favorite"
          }
        }
      },
      "RemoveNoticeFromFavoriteResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Successful operation",
            "example": "Notice successfully remove from favorite"
          }
        }
      },
      "AddNoticeRequest": {
        "type": "object",
        "required": [
          "title",
          "petAvatar",
          "name",
          "birthday",
          "location",
          "type",
          "sex",
          "category",
          "price"
        ],
        "properties": {
          "title": {
            "type": "string",
            "description": "Notice's title",
            "example": "Cute cat looking for a home"
          },
          "petAvatar": {
            "type": "string",
            "description": "Pet's foto link",
            "example": "https://loremflickr.com/640/480/animals"
          },
          "name": {
            "type": "string",
            "description": "Pet's name",
            "example": "Melany"
          },
          "birthday": {
            "type": "string",
            "description": "Pet's birthday",
            "example": "21-09-2023"
          },
          "type": {
            "type": "string",
            "description": "Pet's type",
            "example": "Promeranian"
          },
          "sex": {
            "type": "string",
            "description": "Pet's sex",
            "enum": ["male", "female"],
            "example": "male"
          },
          "comments": {
            "type": "string",
            "description": "Notice's comments",
            "example": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!"
          },
          "location": {
            "type": "string",
            "description": "Pet's city",
            "example": "Barnstable Town"
          },
          "category": {
            "type": "string",
            "description": "Notice's category",
            "enum": ["sell", "lost/found", "in good hands"],
            "example": "lost/found"
          },
          "price": {
            "type": "number",
            "description": "Pet's price",
            "example": "23"
          }
        }
      },
      "AddNoticeResponse": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Notice's title",
            "example": "Cute cat looking for a home"
          },
          "petAvatarURL": {
            "type": "string",
            "description": "Pet's foto link",
            "example": "https://loremflickr.com/640/480/animals"
          },
          "name": {
            "type": "string",
            "description": "Pet's name",
            "example": "Melany"
          },
          "birthday": {
            "type": "string",
            "description": "Pet's birthday",
            "example": "21-09-2023"
          },
          "type": {
            "type": "string",
            "description": "Pet's type",
            "example": "Promeranian"
          },
          "sex": {
            "type": "string",
            "description": "Pet's sex",
            "enum": ["male", "female"],
            "example": "male"
          },
          "comments": {
            "type": "string",
            "description": "Notice's comments",
            "example": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!"
          },
          "location": {
            "type": "string",
            "description": "Pet's city",
            "example": "Barnstable Town"
          },
          "category": {
            "type": "string",
            "description": "Notice's category",
            "enum": ["sell", "lost/found", "in good hands"],
            "example": "lost/found"
          },
          "price": {
            "type": "number",
            "description": "Pet's price",
            "example": "23"
          },
          "owner": {
            "type": "string",
            "description": "Owner's id",
            "example": "534d677fcc8ea74aedaabdc1"
          },
          "idUsersAddedFavorite": {
            "type": "array",
            "description": "User's id who added notice favorite",
            "item": {
              "type": "string",
              "describe": "User's id",
              "example": "64df88ca1f2426eddf5014d7"
            }
          }
        },
        "example": {
          "title": "Cute pet looking for a home",
          "petAvatarURL": "https://loremflickr.com/640/480/animals",
          "name": "Charlie",
          "birthday": "21-09-2023",
          "type": "Promeranian",
          "sex": "male",
          "place": "Little Rock",
          "comments": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!",
          "category": "sell",
          "price": "40",
          "owner": "f24cf26ff2b7a80e999b8abb",
          "idUsersAddedFavorite": [
            "64df88ca1f2426eddf5014d7",
            "75df88ca1f6346eddf5014g6"
          ]
        }
      },
      "GetUserNoticesResponse": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Notice's title",
            "example": "Cute cat looking for a home"
          },
          "petAvatarURL": {
            "type": "string",
            "description": "Pet's foto link",
            "example": "https://loremflickr.com/640/480/animals"
          },
          "name": {
            "type": "string",
            "description": "Pet's name",
            "example": "Melany"
          },
          "birthday": {
            "type": "string",
            "description": "Pet's birthday",
            "example": "21-09-2023"
          },
          "type": {
            "type": "string",
            "description": "Pet's type",
            "example": "Promeranian"
          },
          "sex": {
            "type": "string",
            "description": "Pet's sex",
            "enum": ["male", "female"],
            "example": "male"
          },
          "comments": {
            "type": "string",
            "description": "Notice's comments",
            "example": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!"
          },
          "location": {
            "type": "string",
            "description": "Pet's city",
            "example": "Barnstable Town"
          },
          "category": {
            "type": "string",
            "description": "Notice's category",
            "enum": ["sell", "lost/found", "in good hands"],
            "example": "lost/found"
          },
          "price": {
            "type": "number",
            "description": "Pet's price",
            "example": "23"
          },
          "owner": {
            "type": "string",
            "description": "Owner's id",
            "example": "534d677fcc8ea74aedaabdc1"
          },
          "idUsersAddedFavorite": {
            "type": "array",
            "description": "User's id who added notice favorite",
            "item": {
              "type": "string",
              "describe": "User's id",
              "example": "64df88ca1f2426eddf5014d7"
            }
          }
        },
        "example": [
          {
            "title": "Cute pet looking for a home",
            "petAvatarURL": "https://loremflickr.com/640/480/animals",
            "name": "Charlie",
            "birthday": "21-09-2023",
            "type": "Promeranian",
            "sex": "male",
            "place": "Little Rock",
            "comments": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!",
            "category": "sell",
            "price": "40",
            "owner": "f24cf26ff2b7a80e999b8abb",
            "idUsersAddedFavorite": [
              "64df88ca1f2426eddf5014d7",
              "75df88ca1f6346eddf5014g6"
            ]
          },
          {
            "title": "Cute pet looking for a home",
            "petAvatarURL": "https://loremflickr.com/640/480/animals",
            "name": "Charlie",
            "birthday": "21-09-2023",
            "type": "Promeranian",
            "sex": "male",
            "place": "Little Rock",
            "comments": "Rich would be the perfect addition to an active family that loves to play and go on walks. I bet he would love having a doggy playmate too!",
            "category": "sell",
            "price": "40",
            "owner": "f24cf26ff2b7a80e999b8abb",
            "idUsersAddedFavorite": [
              "64df88ca1f2426eddf5014d7",
              "75df88ca1f6346eddf5014g6"
            ]
          }
        ]
      },
      "RemoveOwnerNoticeResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Successful operation",
            "example": "Notice successfully delete"
          }
        }
      },

      "ErrorBadRequestResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Error message",
            "example": "This text will describe what is wrong with the request body"
          }
        }
      },

      "ErrorConflictEmailResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Error message",
            "example": "Email has already in use"
          }
        }
      },
      "ErrorUnauthorizedResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Error message",
            "example": "Unauthorized"
          }
        }
      },
      "ErrorServerResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Error message",
            "example": "This text will describe what is wrong with the internal server"
          }
        }
      },
      "ErrorNotFoundResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Error message",
            "example": "Not Found"
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
